### ISSUE TITLE
The version of Drake

### ISSUE THREAD

**Issue by hjd-hitsz** [HKUST-Aerial-Robotics/IMPACTOR#3]
The error is 

> quad_model_id = parser.AddModelFromFile(quad_urdf, quad_name)
> AttributeError: 'pydrake.multibody.parsing.Parser' object has no attribute 'AddModelFromFile'

'AddModelFromFile' method is not available in the current version of pydrake, as the figure shows. So I want to now the version used in this code.
![image](https://github.com/user-attachments/assets/380f2e72-0f31-4fa0-9649-bf31f04b557e)
![image](https://github.com/user-attachments/assets/5e6fcfda-9bdf-4593-bc63-8ae550b65d29)

**Comment by haokun-wang** [comment]
Hi @hjd-hitsz ,

Our simulation code was tested in an environment running Ubuntu 20.04 (ROS1 Noetic) with Python 3.8 and **Drake 1.10.0**. You can refer to this configuration to set up your environment (recommended solution).

Additionally, I noted that in the latest version of Drake, the function AddModulesFromUrl() has been introduced to replace the older AddModuleFromFile(). You can consult the [API doc](https://drake.mit.edu/pydrake/pydrake.multibody.parsing.html?highlight=addmodelsfromurl#pydrake.multibody.parsing.Parser.AddModelsFromUrl) for manual replacement of this function.

Best,
Haokun
